emacs-tw/awesome-emacs

- README.org
Add various Emacs packages which are proven useful to me.
> Add packages

- README.org
added technomancy's find-file-in-project
> added find-file-in-project

- README.org
Hi I'd like to add a [jist.el](https://github.com/emacs-pe/jist.el) to the list.
(shameless plug: I wrote this library)
> Add jist.el

- README.org
direct link: https://github.com/joodland/bm
The use case of bm and back-button is more or less similar, so I put them together.
> Add bm package

- README.org
Here it is: https://github.com/leoliu/easy-kill
I've used it for several months and it works fine for me. This package is also on GNU ELPA and its author is very reliable.
> Add easy-kill package

- README.org
A pastebin client for the simple ix.io pastebin
> pastebin: Adding ix.el

- README.org
Add the valuable "The Woodnotes Guide to Emacs for Writers"
> Add The Woodnotes Guide to Emacs for Writers

- README.org
Two links/resources added:
* http://endlessparentheses.com/
* http://whattheemacsd.com/
> more links and resources

- README.org
Another starter kit, @bodil's ohai-emacs
> added @bodil's ohai-emacs to starter kits list

- README.org
Merlin is a very powerfull tool !
> Add merlin (in OCaml section)

- README.org
URL: https://github.com/nicferrier/elnode
> Add elnode

- README.org
Simple  integration package with github/bicbucket websites, allows user target pages in browser
> Add browse-at-remote package

- README.org
Hi,
* elixir-mode - Emacs major mode for Elixir
* alchemist - Elixir Tooling Integration Into Emacs
> add elixir language section

- README.org
Add some useful Emacs packages.
> Add some packages

- README.org
https://github.com/sindresorhus/awesome/issues/253
> Add awesome list badge

- README.org
add exwm(Emacs X Window Manager)
> add exwm(Emacs X Window Manager) in Fun

- README.org
I just changed both my domain and site.
> Change emacs themes site url.

- README.org
Add ergoemacs-mode as a interface change.  You could add CUA as well
> Update README.org to include ergoemacs-mode

- README.org
Added:
* `emacs-racer`,
* `vertigo.el`, and
* `spaceline`
Thanks!
> More links

- README.org
Adding @jcollard's elm-mode, a major mode for http://elm-lang.org/
> Add elm-mode

- README.org
- gen-toc.el
Also fix link for markdown-mode so github can show it properly. 
Edit: and I think the table of contents looks better outside a quoteblock, don't you think?
> add various packages and stop quoting table of contents

- README.org
This is a simple package to create cheatsheet with only defined for cheatsheet keys.
> Added cheatsheet package

- README.org
Created with https://github.com/dkhamsing/frankenstein
Was | Now 
--- | --- 
http://github.com/Bruce-Connor/emacs-google-this | https://github.com/Malabarba/emacs-google-this 
https://github.com/Bruce-Connor/aggressive-indent-mode/ | https://github.com/Malabarba/aggressive-indent-mode 
https://github.com/Bruce-Connor/names | https://github.com/Malabarba/names 
https://github.com/Bruce-Connor/paradox | https://github.com/Malabarba/paradox 
https://github.com/Bruce-Connor/smart-mode-line | https://github.com/Malabarba/smart-mode-line 
https://github.com/attichacker/cargo.el | https://github.com/kwrooijen/cargo.el 
https://github.com/d11wtq/fiplr | https://github.com/grizzl/fiplr 
https://github.com/d11wtq/grizzl | https://github.com/grizzl/grizzl …
> Update README URLs based on HTTP redirects

- README.org
> Changed with Melpa link

- README.org
Updated project and repository name to be melpa compliant
> updated grails minor mode url

- README.org
Signed-off-by: Yen-Chin Lee <coldnew.tw@gmail.com>
> Added ranger.el on File Manager section

- README.org
Signed-off-by: Yen-Chin Lee <coldnew.tw@gmail.com>
> Added clj-refactor.el for Clojure section

- README.org
> Updates to Noteworthy Configurations

- README.org
Add a noteworthy configuration
> Updated Readme

- README.org
Added link to Emacs config of Drew Adams
Changed some incorrect facts and notes
> Updated to Noteworthy Configurations category

- README.org
> Add package

- README.org
Adding http://cestlaz.github.io/stories/emacs/ to Tutorials
> Add 'Using Emacs Series' by @zamansky to Tutorials

- README.org
> Add gotest.el

- README.org
> Add phpunit.el

- README.org
> Add sift.el

- README.org
> Add Dionysos

- README.org
> Add markdownfmt

- README.org
Is this ordering OK? I decided based on the number of GitHub stars.
> Added doom-themes

- README.org
beacon, a light that follows your cursor around so you don't lose it :)
> add beacon

- README.org
Adds mingus (https://github.com/pft/mingus) to the multimedia section
> Add mingus

- README.org
This PR adds following packages:
* [artist-mode](http://cinsk.github.io//emacs/emacs-artist.html)
> Add artist mode to editing

- README.org
Adding fasd integration for emacs. Fasd is a command-line productivity booster
> Adding fasd integration

- README.org
Adding support for terraform mode to edit terraform files
> Adding support for terraform mode

- README.org
Added link to [ialign](https://github.com/mkcms/interactive-align)
> Add ialign to editing section

- README.org
Very beautiful package. I am sad I don't find it here :)
> add org-brain

- README.org
Add 'iy-go-to-char' under 'Navigation'
> Add iy-go-to-char

- README.org
https://hackr.io/tutorials/learn-emacs
> Added Community Curated Resources

- README.org
Something like winner mode in steroids
> add eyebrowse

- README.org
Denis Ogbe - Emacs config link returns 404
Drew Adams - Emacs config link gone
> Removed some links that 404

- README.org
Added csound-mode under the sublist 'Multimedia'.
> Added csound-mode under the sublist 'Multimedia'.

- README.org
Add one of the only syntax highlighting support for molecular dynamics packages.
> lammps-mode: Init

- README.org
This package doesn't have huge stargazers. But it really solve my long standing problem. Especially emacs users who need analog feedback of their current position.
And at the same time they disabled line-numbers and scroll-bar-mode.
[more story](https://twitter.com/_wilfredh/status/1050155492264296450)
> Add yascroll-el

- README.org
Display mode-line information at right of minibuffer.
> Add awesome-tray

- README.org
Hey there, thanks for maintaining this great list :) This adds @lassik's awesome package to the Programming section.
I think I put this one in the right section since it's usable with multiple programming languages, but let me know if you want it somewhere else!
- Cody
> Add format-all-the-code to Programming

- README.org
A mode akin to nyan-mode, only with parrots instead of kittens. Also doubles as a package for rotating text.
> Add parrot under Fun

- README.org
@kunalb's poet theme is awesome!
> Add Poet theme

- LICENSE
- README.org
Live coding is an important aspect of Emacs.
> Added `Emacs Live`to `Interface Enhancement`

- README.org
This is the package I made, which I think is useful and for general purpose. Well, the opinion here is very subjective, feel free to close this down if you think this package shouldn't be on the list. Cheer!
> Add goto-line-preview

- README.org
This is awesome, `magit` is using this library!!
> Add indicators.el

- README.org
Restarting Emacs within Emacs, I think this is useful when user got into terminal only environment.
> Add restart-emacs.

- README.org
> Add google-maps.

- README.org
Awesome blog with a lot of tutorials on emacs/elisp.
> Add ErgoEmacs blog

- README.org
> Add diminish.

- README.org
Awesome package, highlight surrounding parentheses.
> Add highlight-parentheses.

- README.org
Add move-text, awesome package.
> Add move-text.

- README.org
Auto-complete uses this, which is awesome!
> Add pos-tip

- README.org
> Fix Emacs from scratch article URL

- README.org
Added my plugin centaur-tabs. Check it out!
> Added centaur-tabs

- README.org
Added Kaolin themes given it's a popular theme package. Also, fixed Doom themes description given it is a theme pack, not a single theme just as Kaolin themes
> Added Kaolin themes and fixed Doom themes description

- README.org
Metals is a Scala language server with rich IDE features.
Metals supports multiple Editors and IDE's.
https://scalameta.org/metals/
> Added Metals for Scala

- README.org
https://github.com/danielde/org-web
Disclaimer: I'm the author of org-web :)
> Add org-web

- README.org
I suggest adding information on my package [jeison](https://github.com/SavchenkoValeriy/jeison).
> Add information on 'jeison' library

- README.org
Links to the repos:
- Wilmersdorf: https://github.com/ianpan870102/wilmersdorf-emacs-theme
- Tron Legacy: https://github.com/ianpan870102/tron-legacy-emacs-theme
- Yay-Evil Distro: https://github.com/ianpan870102/.emacs.d
> Add wilmersdorf, tron legacy and yay-evil distro

- README.org
Seems like it was about time to address Issue #268 . 
@kuanyui and @Superbil, can you do me a favor and look over this PR. Quite a bit of changes were made, and I put the Installation section near the front, just after the Table of Contents section. I'd like a second pair of eyes to review the changes before this PR is merged/squashed into the project.
Thanks!
> Add Installation Section

- README.org
Address items mentioned in https://github.com/emacs-tw/awesome-emacs/issues/338
> Cleanup "Starter Kit" Section

- README.org
Pretty useful for people working with SVN repositories and those wishing to store large files in git
> Add magit-svn and magit-lfs

- README.org
Rather useful minor mode to make PDF Tools behave more like other GUI readers.
> Add pdf-view-restore

- README.org
Adding an awesome package to deal with forges from Magit:
https://magit.vc/manual/forge/
https://github.com/magit/forge
> Adding magit forge

- README.org
Snails is a modern, easy-to-expand fuzzy search framework.
The goal of this project is to minimize the development threshold for fuzzy search plugins. If you know how to write a filter function, you can write a new search plugin in 5 minutes, regardless of how complex the search framework is.
> Add snails framework

- README.org
Add two projects to the list: https://github.com/federicotdn/verb and https://github.com/federicotdn/key-quiz.
> Add two projects to the list

- README.org
- Include https://github.com/manateelazycat/emacs-application-framework .
- Change sort order of Operating System Section.
- Change some wording.
- Update URL of a github -> gitlab project transition.
- Make sure that previous Travis tests fails should now pass.
> Update Operating System section

- README.org
Few helpful packages when editing go code
> Golang packages

- README.org
Hi all!  Hope this is OK, I'm adding a link to my YouTube series called Emacs From Scratch which guides viewers through the process of creating their own vanilla Emacs configuration.  Let me know if there's anything I need to change!
> Add Emacs From Scratch series to README.org

- README.org
Hi,
I suggest link to [undo-propose](https://github.com/jackkamm/undo-propose-el) mode
> Add undo-propose mode

- README.org
Use Evil-like binding states without predefined keybindings (Evil mode without vi)
> Add multistate mode

- README.org
it works amazingly. I had problems with other packages because i don't have all permissions on some k8s clusters.
>  kubel package for kubernetes management

- README.org
1. Add emacs-winum
2.  Add move-dup (replace move-text completely)
3. Remove duplicate highlight-parentheses
> Add some new library.

- README.org
math-preview now also supports MathML
> Update math-preview description

- README.org
In my case it worked better than highlight-symbol and has more functionality
> add symbol-overlay to visualize section

- README.org
> Fixed org links

- README.org
Add (own) fancy-compilation package, I wanted this functionality for  years and only recently realized it was possible, so I wrapped this up in a package that provides terminal-like output to compilation-mode.
> Add "fancy-compilation" package

- README.org
This package is very handy as a way of quickly completing or correcting spelling without blocking prompts.
> Add recomplete package

- README.org
This package can cycle and scale default fonts.
> Add "default-font-presets"

- README.org
I added the following packages
-transclusion
-deft
-zetteldeft (extension for deft)
The first two have 600+ stars and are mature enough to be referenced in this awesome page
> Org section updated with 3 new packages

- README.org
Add mono-complete package (available on melpa).
> Add mono-complete

- README.org
Add the buffer-name-relative (available in melpa).
> Update README.org: Add buffer-name-relative

- README.org
These tools largely boost the productivity of emacs to my personal experience.
> Adding AI section: copilot and chatgpt

- README.org
I added two packages that my friend Illya Chernyshov created:
- org-timeblock into Org-mode  subcategory
- enlight into Interface Enhancement category
> 2 packages from ichernyshovvv: enlight & org-timeblock

- README.org
> Add Dslide

- README.org
Hello!
First of all, thank you for the incredible work put on creating this list.
I would like to add the package I developed [Whaler.el](https://github.com/salorak/whaler.el) to the Project management category.
From the readme:
> Whaler offers a tailored experience to managing your projects. It is a minimalistic and highly customizable project manager.
Thank you!
> Add Whaler in the Project management section

- README.org
`highlight-indent-guides` has more popularity nowadays.
> feat: Place highlight-indent-guides higher

- README.org
Colorful-mode is the modern replacement for rainbow-mode.
> Add colorful-mode

- README.org
>  A minimal mode-line for emacs which is not highly configurable and doesn't work in terminal
- Kind of similar to those usually seem in Neovim configurations
- Supports ["what I'm doing messages"](https://github.com/konrad1977/punch-line#what-am-i-doing-plugin)
- Previously known as [cocaine-line](https://github.com/konrad1977/cocaine-line) 🤨
> Add punch-line

- README.org
This https://github.com/jcfk/savefold.el
> Add savefold.el

- README.org
Add https://github.com/jcs-elpa/flx-rs.
> Add flx-rs

- README.org
Add https://github.com/ericdallo/jet.el.
> Add jet.el

- README.org
Add https://github.com/joostkremers/writeroom-mode.
> Add writeroom-mode

- README.org
Add https://github.com/bastibe/org-journal
> Add org-journal

- README.org
Add https://github.com/emacs-vs/codemetrics
> Add codemetrics
