emacs-tw/awesome-emacs

- README.org
It is a GNU ELPA package, but not a built-in package.
My bad.
> Remove built-in tag for Names package

- README.org
[Avy](https://github.com/abo-abo/avy) is similalr to [ace-jump-mode](https://github.com/winterTTr/ace-jump-mode) and [vim-easymotion](https://github.com/Lokaltog/vim-easymotion) and less popular than [ace-jump-mode](https://github.com/winterTTr/ace-jump-mode)
> Add Avy package

- README.org
A minor mode for managing a Rust Cargo project.
> Add cargo.el to Rust

- README.org
Lentic allows two buffers to share the same or similar content but otherwise operate independently.
Different buffers can be in the same mode, with different locations of point, even different text sizes 
-- in effect, providing multiple persistent views.
Signed-off-by: Yen-Chin Lee <coldnew.tw@gmail.com>
> Add lentic to Editing section

- README.org
These are most useful (I deduce from GitHub stars and number of downloads from MELPA) and probably most understandable :-D from my packages. I've placed them at the end of every category because I don't think they are really popular even when I think they are better than more popular alternatives. Exception is made for `vimish-fold`, which seems to be better than `hideshow` according to *actual user feedback*. It seems to gain some popularity nowadays.
Package `speed-type` is not mine, but I think it's pretty good, so I added it too.
> Add links to some packages

- README.org
This adds a "jump to definition" section to the programming section. This functionality is often provided via language specific packages that provide additional features for that language. I think it's worth considering adding a section for packages that are devoted to this type of functionality and support multiple languages. Full disclosure: I made Dump Jump.
> add "jump to definition" to programming section

- README.org
helm-ack is no longer maintained. helm-ag can be available instead of helm-ack.
> Remove helm-ack

- README.org
Removed link as it resolves to a 404 now
> Remove Google Client link

- README.org
According to the README, development has moved to
https://github.com/Fanael/rainbow-delimiters
> Fix 'rainbow-delimiters' link

- README.org
Added entry for `ielm` - see https://www.emacswiki.org/emacs/InferiorEmacsLispMode
> Add ielm - an Emacs Lisp REPL

- README.org
Add https://github.com/kelvinh/org-page to the list. I use it for my personal website, and it brilliantly works.
> Add org-page to Blog category

- README.org
Origamil.el is a text folding minor mode for Emacs.
> Add Origami.el - Text folding minor mode 

- README.org
Adds RefTeX (https://www.gnu.org/software/auctex/reftex.html) to the LaTeX section
_RefTEX is a specialized package for support of labels, references, citations, and the indices in LATEX._
> Add RefTeX

- README.org
`projectile` and `speedbar` don't work together out of the box. This small package fills in the gap.
> Add projectile-speedbar package link

- README.org
Evil has moved to https://github.com/emacs-evil/evil.
> Update the url to Evil repo

- README.org
Adds two modes for MIPS and RISCV assembly. I wrote one of them, and heavily contributed to the other.
> Add MIPS & RISCV Assembly modes

- README.org
This PR adds:
* Link to [verilog-mode](https://github.com/veripool/verilog-mode) for emacs
> Add verilog-mode

- README.org
Scimax is a starter kit for scientists and engineers with lots of goodies for Org-Mode.
> Add scimax to starter kits.

- README.org
Links for Ensime and Org-mode were throwing 300-level redirects on the
Travis builds, so I've updated them to point to the right places.
This should fix the failed builds on the open PRs.
> Update links for Ensime and Org-mode (Fix Breaking Builds)

- README.org
Frontmacs is a package-based, web-centric, customizable,
awesome-by-default, acceptance-tested Emacs distribution curated by
your friends at Frontside.
We've been using Emacs for years here at Frontside, and have finally
decided to share the configuration for our favorite editor with the world.
Read more about Frontmacs here:
https://github.com/thefrontside/frontmacs
> Add Frontmacs to 'Starter Kit' Section

- README.org
Note that most of the effort for writing Evil bindings is focused on Evil Collection, thus the list is unlikely to grow.
> Add Evil bindings modes

- README.org
Added ledger-mode, a wrapper for the ledger command line utility for plain-text accounting. I ommited the slightly less popular hledger-mode, which is a frontend for hledger, the haskell alternative to ledger.
> Add ledger-mode for plain text accounting

- README.org
Arguably a precious standard isn't an inherently wrong statement, but I highly doubt it's what's intended.
> Fix Typos and Grammatical Errors in README.org

- README.org
Add xah-fly-keys to the Interface Enhancement section. Xah-fly-keys is a modal keybinding for emacs (like vim), but based on command frequency and ergonomics.
[Link to the repo](https://github.com/xahlee/xah-fly-keys)
> Add xah-fly-keys to the Interface Enhancement

- README.org
I'm starting to try out general (https://github.com/noctuid/general.el#about) and it seems very handy. I noticed that it wasn't on the list so I added it in. Looking at the contribution guidelines, I know that you said that the ordering should be based on the popularity of the package. The correct ordering would be: 
1. Evil
2. Hydra
3. god-mode 
4. general
5. ergoemacs-mode 
6. modalka
7. xah-fly-keys 
But also, I wasn't sure if that meant ordering for the overall list or just inner lists - so I just tacked on general at the end.
> Added in the package general for key-binding packages

- README.org
Adding deadgrep by Wilfred (author of ag.el), ordered it above ripgrep.el as its features are more aligned towards parent category of searching.
> Added deadgrep by Wilfred under Ripgrep

- README.org
Out of box extension to use tab in Emacs, build-in projectile support and many awesome features.
> Add awesome-tab.el

- README.org
Hey,
Kubernetes-el is a great tool for working with Kubernetes clusters. It provides an interface like *Magit* (<3) to show info about deployments, pods and such, as well as commands you usually perform with *kubectl*.
Link: https://github.com/chrisbarrett/kubernetes-el
> Added kubernetes-el to the DevOps section

- README.org
I found this package `highlight-indent-guides` recently. This is very nice to me for editing long YAML, JSON, HTML, JSX, etc.!
So this PR suggests adding the package to the awesome list.
The repository is <https://github.com/DarthFennec/highlight-indent-guides>.
Note:
I added it to the `Appearance` category, but if there is a category more suitable for the package, then please tell me. I'm preparing for a change.
> Add highlight-indent-guides

- README.org
https://www.reddit.com/r/emacs/comments/asa061/httpplanetemacsenorg_is_down/
https://github.com/hober/planet.emacsen.org
https://planet.emacslife.com/
Providing these links and resources until the original Planet Emacsen URL is restored.
> Planet Emacsen temporary workaround

- README.org
- Added a debugging section since this might be quite important to some and realgud was almost hidden in the middle of the current programming section
- Move realgud and add dap-mode to debugging section
- Add doom-modeline and all the icons under visual
- Add caiorss elisp/Emacs configuration tutorial
- Add rustic to rust section
- Add lsp-ui to programming section
- Add magit-todo to magit section
- Add org-super-agenda and org-interleave to org section
- Add mastodon client to social section
- Add elfeed-org to web feed section
- Reorder the keys section by popularity which will partially fix #273
> Add Debugging section. Add modeline, org, rust and other packages

- README.org
Functions to keep TODO tasks in orgmode sorted and organized.
You can sort an unsorted TODO list using mergesort with `org-sort-tasks`. The fn will try to find which task is more important taking into account deadline, scheduled time, priority and then, if everything is equal, finally ask to the user.
When the list is already sorted, you can use fn `org-insert-sorted-todo-heading` to insert a task in a right position using binary search.
> Adding `org-sort-tasks` lib.

- README.org
Direct link here: https://github.com/jcaw/theme-magic
This is my package, so I don't know if it's frowned upon for me to request it be added.
> Add `theme-magic` to Integration/Operating system

- README.org
The old repo link is no longer the official source, it has moved.
> Update speed-type repo link to new official source

- README.org
`cmake-ide` is improving autocompletion since it uses the compilation database cmake can provide to consider compile options like include paths, defines and other flags to irony, rtags and other packages. Without it completion might be wrong or incomplete.
> Add cmake-ide to C++ section

- README.org
I suggest adding information on my package [emacs-powerthesaurus](https://github.com/SavchenkoValeriy/emacs-powerthesaurus).
I don't really know which category suites it better. I thought that **Note** would do, but **Integrations** also makes a reasonable choice.
> Add information on powerthesaurus.org integration

- README.org
Intero is arguably the most full featured Haskell environment available for Emacs and thus should be recommended to every newbie.
> Move intero higher up the Haskell list

- README.org
Awesome-tab now removes the dependency on projectile, and uses built in project.el.
> Update informations about awesome-tab.

- README.org
And I can't find any emacs's config on https://github.com/lunaryorn/ , so remove it.
> Remove Sebastian Wiesner's emacs config since url missing

- README.org
With this PR:
Without this PR:
> Add Emacs icon to make README.org looks fancy on GitHub

- README.org
Also add a note that git-gutter is unmaintained and fix some grammatical errors.
> Add diff-hl

- README.org
The link for pdf-view-restore was missing a "]".
> Fixed typo on PDF-view-restore

- README.org
I initially forked to add racket-mode to the list because I didn't see it on there. Then I realized it was listed under scheme. I think this will help discoverability of racket-mode
> Move racket into its own category

- README.org
These are nice packages having undo/redo and saving undo history across sessions.
`undo-fu` advertises itself as being simpler than Undo Tree, and so hopefully more stable. It is used by Doom Emacs, among others.
> Add packages undo-fu and undo-fu-session.

- README.org
Accessible themes for GNU Emacs, conforming with the highest accessibility
standard for colour contrast between background and foreground values (WCAG AAA
standard).
> Add Modus themes.

- README.org
Icomplete (built-in) is similar to Ido in that displays a list of candidates
while completing, but unlike Ido, Icomplete works for any completion command by
default.
icomplete-vertical is a third-party package that makes Icomplete display
candidates vertically, like in Ivy or Helm.
> Add Icomplete and icomplete-vertical.

- README.org
From the README:
This package provides an orderless completion style that divides the pattern
into space-separated components, and matches candidates that match all of the
components in any order. Each component can match in any one of several ways:
literally, as a regexp, as an initialism, in the flex style, or as multiple word
prefixes. By default, regexp and initialism matches are enabled.
A completion style is a back-end for completion and is used from a front-end
that provides a completion UI. Any completion style can be used with the default
Emacs completion UI (sometimes called minibuffer tab completion) or with the
built-in Icomplete package (which is similar to the more well-known Ido
Mode). To use a completion style in this fashion simply add it as an entry in
the variables …
> Add Orderless, a completion style to match search terms in any order.

- README.org
Hi,
I thought it would make sense to add a config management section for packages which help maintaining your `.emacs.d`. I moved `esup` and `chemacs` to this section and also added a few others.
> Add config management section

- README.org
Add [math-preview](https://gitlab.com/matsievskiysv/math-preview) package. It provides visual preview when editing TeX equations. It's not limited to just TeX or Markdown, so it belongs to `Visual` section.
> Add math-preview package

- README.org
This adds raku-mode under Programming Languages and removes leading
spaces from 2 lines.
> Add raku-mode, remove leading spaces

- README.org
Added  [emacs-gdscript-mode](https://github.com/godotengine/emacs-gdscript-mode) to the programming language section, as well added missing Raku link to the Table of Contents section.
> Add gdscript-mode

- README.org
I've recently been using this package to show detailed information based on the position in the document, that would typically reduce performance.
Examples include:
- The title of the current doxygen section (for C/C++ code).
- Accumulate time stamps to show hours worked.
- Word count.
Note, I'm the author of this package.
> Suggest `mode-line-idle`

- README.org
According to [README](https://github.com/m0smith/malabar-mode#malabar-is-moving-to-jdee) malabar is now part of JDEE which have number of opened issues, missing documentation and is [not maintained](https://github.com/jdee-emacs/jdee/commits/master) since 2 years.
> Remove JDEE and malabar-mode

- README.org
0x0.st is a FOSS url shortening / file sharing service.
There is a frontend for the same.
It is available on melpa
> Add 0x0.st to pastebin services

- README.org
The origianl pdf-tools is not being maintained anymore. Changed the link to the currently maintained fork.
> Change pdf-tools repo

- README.org
pkal has written this on his repository that's currently linked:
> [William Vaughn](https://gitlab.com/willvaughn/emacs-0x0) has taken over the development of this package on Gitlab. I do not intend to further work on this repository.
I've corrected the link to Vaughn's repo on Gitlab as provided by Philip.
> Correct the URL for 0x0

- README.org
Update Better Defaults to show new host and add two new kits: Emacs From Scratch and Emacs Starter Kit
> Update & add emacs starter kits

- README.org
[EDNC](https://github.com/sinic/ednc) might not be especially well-known, but as far as I can tell there's no other package in MELPA that acts as a notification server, so it fills a gap.
I put it next to EXWM, because it's probably most useful for users of that window manager. It's not a requirement, however, so I made the entry a sibling instead of a child.
**Disclosure**: I'm the author of this package.
> Add the Emacs Desktop Notification Center

- README.org
This package is excellent, allowing quick tree navigation on-top of Emacs built-in undo system.
I've been using it for ~4 months now and since some issues were fixed early on it's been rock solid.
With undo-fu/undo-fu-sessioin/vundo - it it's possible to have undo-tree's functionality but with emacs built-in undo.
> Add "vundo" (undo tree structure navigation)

- README.org
Add `fzf.el` to the **Integration -> Console** section. **Minibuffer -> Fuzzy / Narrowing** didn't seem like the right place because this doesn't do anything with the mini buffer, it's a thin interface on top of `fzf` that runs in a regular buffer. I recommend it as a lightweight alternative to things like `projectile` and `helm` if you find yourself only using a small fraction of the many loc there.
> add fzf.el

- README.org
Added this package, it has similar goals to `highlight-symbol` but has some advantages since it only operates on visible area(s) instead of using hard-coded number of lines for narrowing, it has more downloads on melpa too, although I don't mean to say the other package is bad, just that this works well for large buffers in my experience.
NOTE: I'm not the original author of the package but I do maintain it.
> Add idle-highlight-mode

- README.org
Add hl-indent-scope which works differently to the existing indentation highlighting packages by using the code's scope
Works with C-like/Lisp-like languages as well as CMake and Python.
To get a quick idea how this package differs from the others on this list see: https://user-images.githubusercontent.com/1869379/182262397-f4dd8950-8554-4cc2-a035-3ee0bace91e1.png
> Add hl-indent-scope

- README.org
Hello,
this PR introduces the following changes:
- Fixed the indentation of toc-org
- Placed deft / zetteldeft above the org subsection as they do not belong to it
- Added an alternative to Yasnippet called Tempel in the snippet section
> Note section reorganised and new snippet package

- README.org
The closing `]` is in the wrong place.
> Fix vundo link formatting

- README.org
`intero` has been discontinued long time ago, and in the meantime `dante` seems to have taken its place.
> Replace intero with dante for Haskell development

- README.org
I was divided on whether to place this above or below org-bullets. On one hand, org-modern is actively maintained and has more github stars, on the other, org-bullets has many more downloads on melpa. I ended up putting it below org-bullets, but I don't know if it would be better to place it back above it.
>  Adds package org-modern to Org section 

- README.org
I've taken the liberty of adding the following packages: 
- `emmet2` which is more fresh than the `emmet` package and offers better compatibility with the upstream Emmet, due to relying on the `npm` package for the logic and not a rewrite in Elisp. 
- `expreg` an actively maintained version of `expand-region` that leverages `tree-sitter`.
- `electric-operator`, it's a nice package that inserts spaces where they belong. 
- `Ellama` as both a coding assistant **and** GPT shell. 
- `tabby-mode` as a coding assistant.
- Moved `org-ai` above chatGPT interfaces, because it is both more general and less dependent on proprietary paid services.
> Add `emmet2`, `electric-operator`, `expreg`, `ellama`, `tabby-mode`

- README.org
[kele.el](https://github.com/jinnovation/kele.el) is a new Emacs package that provides a performant, scalable layer for Kubernetes cluster management within Emacs. It sets itself apart from existing solutions ([kubernetes-el](https://github.com/kubernetes-el/kubernetes-el) and [kubel](https://github.com/abrochard/kubel)) in the following ways:
- A focus on resource agnosticism: We make every effort to source resource-specific information from the Kubernetes API itself as opposed to hard-coding logic in the Emacs layer;
- A focus on minimal obtrusion and context-switching, i.e. getting out of users' way as quickly as possible.
More comparison notes in the kele.el docs [here](https://jonathanj.in/kele.el/explanations/comparisons/).
> Add kele.el to DevOps section

- README.org
The [outline-indent](https://github.com/jamescherti/outline-indent.el) Emacs package provides a minor mode that enables code folding and outlining based on indentation levels for various indentation-based text files, such as YAML, Python, and any other indented text files.
In addition to code folding, `outline-indent` allows moving indented subtrees up and down, promoting and demoting sections to adjust indentation levels, customizing the ellipsis, and inserting a new line with the same indentation level as the current line, among other features.
The `outline-indent` package utilizes the built-in *outline-minor-mode*, which is *maintained by the Emacs developers* and is less likely to be abandoned like *origami.el* or *yafolding.el*. Since `outline-indent.el` is based on …
> Add outline-indent

- README.org
Add *Session management* section that contains:
- [desktop](https://www.gnu.org/software/emacs/manual/html_node/emacs/Saving-Emacs-Sessions.html#Saving-Emacs-Sessions) (built-in): Save and restore the state of your Emacs environment.
- [easysession](https://github.com/jamescherti/easysession.el) -  A lightweight session manager that persists and restores Emacs frames (including the tab-bar), file editing buffers, indirect buffers (clones), and Dired buffers.
> Add desktop.el and easysession

- README.org
Add [minimal-emacs.d](https://github.com/jamescherti/minimal-emacs.d), which offers a starter kit with improved Emacs defaults and optimized startup, designed to serve as a robust foundation for your vanilla Emacs configuration and enhance your overall Emacs experience.
> Add minimal-emacs.d

- README.org
This pull request adds the [vim-tab-bar](https://github.com/jamescherti/vim-tab-bar.el) package which enhances Emacs' built-in tab-bar, giving it a style similar to Vim's tabbed browsing interface. 
It also ensures that the tab-bar's appearance aligns with the current theme's overall color scheme, providing a consistent look for your Emacs tab-bar.
> Add vim-tab-bar

- README.org
This PR add AI assistant programming sub section under AI section. Introduced two packages.
> Add AI assistant programming section under AI

- README.org
This PR resolves the links flagged by awesome-bot.
Changes made:
- Updates the redirect links to the actual links (done for `tabby-mode`, `desktop`, and `slack`)
- Fixes the 404 for Sacha Chua's blog
- Removes the emacs for writers link - I couldn't find the original blog post anywhere
> Resolved links flagged by awesome bot

- README.org
This PR adds the following packages:
- [cape](https://github.com/minad/cape) - a package by the creator of [corfu](https://github.com/minad/corfu), it provides completion at point extensions. I added this package as a sub-bullet to `cape`.
- [lspce](https://github.com/zbelial/lspce) - another LSP implementation - I've yet to try this one, but I have found interesting notes on it on [reddit](https://www.reddit.com/r/emacs/comments/1c0v28k/lspmode_vs_lspbridge_vs_lspce_vs_eglot/)
- [eldoc-box](https://github.com/casouri/eldoc-box) - childframes for eldoc - I added this as a sub-bullet to `eldoc`
> Add cape, lspce, and eldoc-box

- README.org
I believe `centaur-tabs` is more popular among tab-bar packages.
> Move centaur-tabs up

- README.org
> Fast, configurable indentation guide-bars for Emacs
> Add indent-bars

- README.org
Built-in command for aligning text. Also supports regular expressions.
Built-in command for replacing text. Also supports regular expressions.
> A nicer interface for query-replace on Emacs
Implements visual commands using built-in functionality.
> Massive Edit: align, query-replace, visual-replace

- README.org
Minuet is a code-completion plugin provide an overlay-based ghost text interface (similar to copilot). An alternative minibuffer completion interface is also provided. It can works with multiple popular LLMs including OpenAI, Claude, Gemini, and more. The user can also choose local LLMs for code completion including Ollama or Llama.cpp.
> Add minuet-ai.el

- README.org
which-key is now included with Emacs 30.
Prelude now requires version Emacs 25+. Removed version reference entirely and updated wording to keep it generalized.
> Add built-in tag to which-key. Update Prelude description.

- README.org
> This packages tries to smartly go to definition leveraging several methods to do so.
> If one method fails, this package will go on to the next one, eventually falling back to the default xref.
I am using this package with dumb-jump, smart-jump is very useful to jump to definition. :)
> Add smart-jump

- README.org
Add the compile-angel package.
The compile-angel package automatically byte-compiles and native-compiles Emacs Lisp libraries. It offers:
- (compile-angel-on-load-mode): A global mode that compiles .el files before they are loaded.
- (compile-angel-on-save-local-mode): A local mode that compiles .el files whenever the user saves them.
The compile-angel modes speed up Emacs by ensuring all libraries are byte-compiled and native-compiled. Byte-compilation reduces the overhead of loading Emacs Lisp code at runtime, while native compilation optimizes performance by generating machine code specific to your system.
- [compile-angel.el @GitHub](https://github.com/jamescherti/compile-angel.el)
- [compile-angel.el @MELPA](https://melpa.org/#/compile-angel)
> Add compile-angel

- README.org
The **inhibit-mouse** package allows the disabling of mouse input in Emacs using `inhibit-mouse-mode`.
Instead of modifying the keymap of its own mode as the disable-mouse package does, enabling inhibit-mouse-mode only modifies input-decode-map to disable mouse events, making it more efficient and faster than disable-mouse.
Additionally, the *inhibit-mouse* package allows for the restoration of mouse input when `inhibit-mouse-mode` is disabled.
- [inhibit-mouse.el @GitHub](https://github.com/jamescherti/inhibit-mouse.el)
- [inhibit-mouse.el @MELPA](https://melpa.org/#/inhibit-mouse)
> Add inhibit-mouse

- README.org
Casual is a collection of Transient user interfaces for various built-in Emacs modes. This commit adds multiple links from Casual to highlight its offering to a particular section.
Support for third party (non built-in) Emacs modes is handled with a separate repo/package. Examples of this include Casual Avy and Casual Symbol Overlay.
Casual Suite is an umbrella package that includes all Casual user interfaces, both built-in and third party.
> Added links to Casual and Casual Suite

- README.org
> Automatically create a tab per project, providing a light tab-bar based workspace management for Emacs
Activates `tab-bar-mode` when opening a project.
> Add otpp.el

- README.org
https://github.com/douo/magit-gptcommit
Generate git commit messages on Magit using LLM providers, for example: OpenAI ChatGPT, Google Gemini, and more.
> Add magit-gptcommit

- README.org
3 new packages to handle Org Mode tables
- `orgtbl-aggregate` creates a summary from a source table, by computing partial sums, averages, and so on.
- `orgtbl-join` enriches an Org Mode table with reference material from other tables.
- `orgtbl-fit` does regression fitting on an Org Mode table.
> add orgtbl-aggregate, orgtbl-join, orgtbl-fit

- README.org
Add built-in `treesit.el` and https://github.com/emacs-tree-sitter/elisp-tree-sitter
> Add Tree-sitter

- README.org
Add treesit-auto, it automatically setup and use the built-in tree-sitter, by installing grammars and using tree-sitter major modes.
> Add treesit-auto

- README.org
Hello. The current version of wttrin on Melpa has changed. The old version broke a while ago. Since then, I've taken over the package, fixed a bunch of bugs, and am adding enhancements. People running across this old link should be pointed to the current version, not the old broken one. Thanks!
> Update wttrin to current Melpa working version  
